"""Add native prompt caching fields to llm_interactions

Revision ID: 9b55dec0a2cd
Revises: 28c32f5eda9b
Create Date: 2025-07-19 14:59:36.690780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b55dec0a2cd'
down_revision: Union[str, None] = '28c32f5eda9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prompt_templates_name_version_key', 'prompt_templates', type_='unique')
    op.create_index('idx_prompt_templates_name_version', 'prompt_templates', ['name', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_templates_name_version', table_name='prompt_templates')
    op.create_unique_constraint('prompt_templates_name_version_key', 'prompt_templates', ['name', 'version'])
    # ### end Alembic commands ###
